-- Case data is accessed only by authenticated Next.js route handlers through a
-- server-side Postgres connection. It is not exposed through Supabase Data API.
CREATE SCHEMA IF NOT EXISTS app_private;
REVOKE ALL ON SCHEMA app_private FROM PUBLIC, anon, authenticated;

CREATE TABLE IF NOT EXISTS app_private.clio_tokens (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  access_token TEXT NOT NULL,
  refresh_token TEXT,
  expires_at BIGINT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS app_private.matters (
  id BIGINT PRIMARY KEY,
  display_number TEXT,
  description TEXT,
  raw TEXT NOT NULL,
  synced_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS app_private.items (
  kind TEXT NOT NULL,
  clio_id BIGINT NOT NULL,
  matter_id TEXT NOT NULL,
  date TEXT,
  title TEXT,
  body TEXT,
  raw TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  synced_at TEXT NOT NULL,
  PRIMARY KEY (kind, clio_id)
);
CREATE INDEX IF NOT EXISTS items_matter ON app_private.items (matter_id, date);
CREATE TABLE IF NOT EXISTS app_private.sync_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matter_id TEXT,
  started_at TEXT NOT NULL,
  report TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS app_private.digests (
  matter_id TEXT NOT NULL,
  version INTEGER NOT NULL,
  input_hash TEXT NOT NULL,
  json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (matter_id, version)
);
CREATE TABLE IF NOT EXISTS app_private.case_snapshots (
  matter_id TEXT PRIMARY KEY,
  json TEXT NOT NULL,
  created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS app_private.shares (
  token TEXT PRIMARY KEY,
  matter_id TEXT NOT NULL,
  config TEXT NOT NULL,
  created_at TEXT NOT NULL,
  revoked_at TEXT
);
CREATE TABLE IF NOT EXISTS app_private.share_views (
  token TEXT NOT NULL,
  viewed_at TEXT NOT NULL,
  who TEXT
);
CREATE TABLE IF NOT EXISTS app_private.matter_views (
  user_id TEXT NOT NULL,
  matter_id TEXT NOT NULL,
  last_viewed_at TEXT NOT NULL,
  PRIMARY KEY (user_id, matter_id)
);
CREATE TABLE IF NOT EXISTS app_private.case_documents (
  id TEXT PRIMARY KEY,
  matter_id TEXT NOT NULL,
  title TEXT NOT NULL,
  origin TEXT NOT NULL,
  provider_name TEXT,
  mime_type TEXT,
  file_path TEXT,
  content_hash TEXT,
  scan_json TEXT,
  created_at TEXT NOT NULL,
  scanned_at TEXT
);
CREATE INDEX IF NOT EXISTS case_documents_matter ON app_private.case_documents (matter_id, created_at DESC);
CREATE TABLE IF NOT EXISTS app_private.case_document_blobs (
  id TEXT PRIMARY KEY REFERENCES app_private.case_documents(id) ON DELETE CASCADE,
  data BYTEA NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS app_private.case_workflows (
  id TEXT PRIMARY KEY,
  matter_id TEXT NOT NULL,
  document_id TEXT,
  kind TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS case_workflows_matter ON app_private.case_workflows (matter_id, created_at DESC);
CREATE TABLE IF NOT EXISTS app_private.case_fact_reviews (
  id TEXT PRIMARY KEY,
  matter_id TEXT NOT NULL,
  document_id TEXT NOT NULL,
  fact TEXT NOT NULL,
  evidence_json TEXT NOT NULL,
  created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS app_private.case_settlements (
  matter_id TEXT PRIMARY KEY,
  amount_cents BIGINT NOT NULL,
  settled_on TEXT NOT NULL,
  source_note TEXT NOT NULL,
  show_amount_to_provider INTEGER NOT NULL DEFAULT 0,
  firm_notice TEXT NOT NULL,
  provider_notice TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- Defense in depth; the schema is already inaccessible to anon/authenticated.
DO $$
DECLARE table_name TEXT;
BEGIN
  FOR table_name IN SELECT tablename FROM pg_tables WHERE schemaname = 'app_private' LOOP
    EXECUTE format('ALTER TABLE app_private.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('REVOKE ALL ON app_private.%I FROM PUBLIC, anon, authenticated', table_name);
  END LOOP;
END $$;
